# Generated by Django 5.1.5 on 2025-02-05 21:17

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Komentár')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
