# Generated by Django 5.1.5 on 2025-02-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
