# Generated by Django 5.1.5 on 2025-02-05 21:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0005_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Názov článku')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Obsah článku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Vymazaný')),
                ('visibility', models.CharField(choices=[('public', 'Verejný'), ('private', 'Súkromný')], default='public', max_length=10, verbose_name='Viditeľnosť')),
            ],
        ),
    ]
