# Generated by Django 5.1.5 on 2025-02-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Krátky popis'),
        ),
    ]
