# Generated by Django 5.1.5 on 2025-02-07 22:35

import peter_pekny_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0007_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=peter_pekny_page.models.article_image_upload_path, verbose_name='Obrázok'),
        ),
    ]
