# Generated by Django 5.1.5 on 2025-03-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0010_comment_article_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
