# Generated by Django 5.1.5 on 2025-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peter_pekny_page', '0012_alter_article_options_article_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
