name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout python project Peter Pekny fun page
        uses: actions/checkout@v4

      - name: Nasadenie na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "$(date) : Deployment Start" >> /tmp/python-deployment.log
            cd ~
            cd django_project >> /tmp/python-deployment.log
            git pull origin main >> /tmp/python-deployment.log
            source ../venv/bin/activate >> /tmp/python-deployment.log
            pip install -r requirements.txt >> /tmp/python-deployment.log
            #python3 manage.py migrate >> /tmp/python-deployment.log
            mv /home/django_project/django_project/staticfiles/ /tmp/staticfiles/ >> /tmp/python-deployment.log
            python3 manage.py collectstatic --noinput >> /tmp/python-deployment.log
            sudo /bin/systemctl restart gunicorn.service >> /tmp/python-deployment.log
            sudo /bin/systemctl status nginx.service >> /tmp/python-deployment.log
            echo "$(date) : Deployment finish" >> /tmp/python-deployment.log
            echo "$(date) : Deployment executed" >> /tmp/python-deployment-log.log