name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout python project Peter Pekny fun page
        uses: actions/checkout@v4

      - name: Nasadenie na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~
            cd django_project
            git pull origin main
            #source ../venv/bin/activate
            #pip install -r requirements.txt
            #python3 manage.py migrate
            #python3 manage.py collectstatic --noinput
            #sudo /bin/systemctl status gunicorn.service
            #sudo /bin/systemctl status nginx.service
            echo "$(date) : Deployment successful"
            echo "$(date) : Deployment successful" >> /tmp/python-deployment.log